# Generated by Django 4.1.6 on 2023-04-16 17:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='random_uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='Случайный UUID'),
        ),
        migrations.AlterField(
            model_name='personusage',
            name='date_of_use',
            field=models.DateTimeField(db_index=True, verbose_name='Дата использования'),
        ),
    ]
