# Generated by Django 4.1.6 on 2023-06-02 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_person_random_uuid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('price_to_alert', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
