# Generated by Django 4.1.6 on 2023-02-15 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_persondata_city_alter_persondata_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persondata',
            name='birth_date',
            field=models.DateField(blank=True, default=None, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='persondata',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='Электронная почта'),
            preserve_default=False,
        ),
    ]
