# Generated by Django 4.1.6 on 2023-06-03 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_cryptoobject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptoobject',
            name='name',
            field=models.CharField(choices=[('bitcoin', 'BTC'), ('ethereum', 'ETH'), ('tether', 'USDT'), ('bnb', 'BNB'), ('usd-coin', 'USDC'), ('xrp', 'XRP'), ('cardano', 'ADA'), ('dogecoin', 'DOGE'), ('solana', 'SOL'), ('polygon', 'MATIC')], max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='cryptoobject',
            name='price_to_alert',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
