# Generated by Django 4.1.6 on 2023-06-06 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_cryptoobject_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptoobject',
            name='price_to_alert',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Стоимость'),
        ),
    ]
