# Generated by Django 4.1.6 on 2023-06-06 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_cryptoobject_price_to_alert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptoobject',
            name='price_to_alert',
            field=models.FloatField(verbose_name='Стоимость'),
        ),
    ]
