# Generated by Django 4.1.6 on 2023-02-15 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_persondata_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persondata',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
    ]
