# Generated by Django 4.1.6 on 2023-02-16 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_persondata_comment_delete_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(blank=True, max_length=50, verbose_name='Фамилия')),
                ('first_name', models.CharField(blank=True, max_length=50, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, max_length=50, verbose_name='Отчество')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Электронная почта')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Номер телефона')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Адрес')),
                ('city', models.CharField(blank=True, max_length=50, verbose_name='Город')),
                ('comment', models.CharField(blank=True, max_length=255, verbose_name='Комментарий')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.country', verbose_name='Страна')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.region', verbose_name='Регион')),
                ('tags', models.ManyToManyField(blank=True, to='core.persontag', verbose_name='Теги')),
            ],
            options={
                'verbose_name': 'Данные абонента',
                'verbose_name_plural': 'Данные абонента',
            },
        ),
        migrations.RemoveField(
            model_name='personusage',
            name='person',
        ),
        migrations.DeleteModel(
            name='PersonData',
        ),
        migrations.DeleteModel(
            name='PersonUsage',
        ),
    ]
