# Generated by Django 4.1.6 on 2023-02-16 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_person_remove_personusage_person_delete_persondata_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonUsage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_use', models.DateTimeField(auto_now_add=True, verbose_name='Дата использования')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.person', verbose_name='Абонент')),
            ],
        ),
    ]
