# Generated by Django 4.1.6 on 2023-02-16 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_personusage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personusage',
            name='person',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='core.person', verbose_name='Абонент'),
        ),
    ]
