# Generated by Django 4.1.6 on 2023-02-19 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_datamapping'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoadedTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents/')),
                ('columns', models.JSONField(default=list)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='DataMapping',
        ),
    ]
