# Generated by Django 4.1.6 on 2023-02-19 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_loadedtable_delete_datamapping'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loadedtable',
            options={'verbose_name': 'Загруженная таблица', 'verbose_name_plural': 'Загруженные таблицы'},
        ),
        migrations.AddField(
            model_name='loadedtable',
            name='field_mappings',
            field=models.JSONField(blank=True, null=True, verbose_name='Сопоставление полей'),
        ),
        migrations.AlterField(
            model_name='loadedtable',
            name='columns',
            field=models.TextField(verbose_name='Столбцы таблицы'),
        ),
        migrations.AlterField(
            model_name='loadedtable',
            name='file',
            field=models.FileField(upload_to='uploads/%Y/%m/', verbose_name='Файл таблицы'),
        ),
        migrations.AlterField(
            model_name='loadedtable',
            name='status',
            field=models.CharField(choices=[('U', 'Unprocessed'), ('M', 'Mapping'), ('P', 'Processed')], default='U', max_length=1, verbose_name='Статус'),
        ),
    ]
