# Generated by Django 4.1.6 on 2023-02-19 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_loadedtable_options_loadedtable_field_mappings_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoadedTable',
        ),
    ]
