# Generated by Django 4.1.6 on 2023-02-19 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_loadedtable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loadedtable',
            name='file',
            field=models.FileField(upload_to='uploads/%Y/%m/%d/', verbose_name='Файл таблицы'),
        ),
    ]
