# Generated by Django 4.1.6 on 2023-02-19 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_loadedtable_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loadedtable',
            name='status',
            field=models.CharField(choices=[('U', 'Unprocessed'), ('M', 'Mapping'), ('P', 'Processed')], default='U', max_length=2, verbose_name='Статус'),
        ),
    ]
