# Generated by Django 4.1.6 on 2023-02-21 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_loadedtable_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loadedtable',
            name='field_mappings',
        ),
        migrations.AlterField(
            model_name='loadedtable',
            name='file',
            field=models.FileField(upload_to='documents/%Y/%m/', verbose_name='Файл таблицы'),
        ),
    ]
