# Generated by Django 4.1.6 on 2023-02-21 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_loadedtable_field_mappings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loadedtable',
            name='status',
            field=models.CharField(choices=[('U', 'Unprocessed'), ('M', 'Mapping'), ('P', 'Processed')], default='U', max_length=1, verbose_name='Статус'),
        ),
    ]
