# Generated by Django 4.1.6 on 2023-02-28 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_loadedtable_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='person/table/%Y/%m/', verbose_name='Файл таблицы')),
                ('columns', models.TextField(verbose_name='Столбцы таблицы')),
                ('status', models.CharField(choices=[('U', 'Необработанно'), ('M', 'Сопоставление'), ('P', 'Обработанно')], default='U', max_length=1, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Загруженная таблица',
                'verbose_name_plural': 'Загруженные таблицы',
            },
        ),
        migrations.DeleteModel(
            name='LoadedTable',
        ),
    ]
