# Generated by Django 4.1.6 on 2023-02-28 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_persontable_delete_loadedtable'),
    ]

    operations = [
        migrations.RunSQL("TRUNCATE TABLE core_persontable;"),
        migrations.AlterField(
            model_name='persontable',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Необработанно'), (1, 'Сопоставление'), (2, 'Обработанно')], default=0, verbose_name='Статус'),
        ),
    ]
