# Generated by Django 4.1.6 on 2023-02-28 06:42

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_persontable_status'),
    ]

    operations = [
        migrations.RunSQL("TRUNCATE TABLE core_persontable;"),
        migrations.AlterField(
            model_name='persontable',
            name='columns',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), size=None, verbose_name='Столбцы таблицы'),
        ),
    ]
