# Generated by Django 4.1.6 on 2023-02-28 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_persontable_columns'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persontable',
            old_name='file',
            new_name='filename',
        ),
    ]
