# Generated by Django 4.1.6 on 2023-03-02 13:39

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_rename_file_persontable_filename'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persontable',
            old_name='filename',
            new_name='file',
        ),
        migrations.AlterField(
            model_name='persontable',
            name='columns',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None, verbose_name='Столбцы таблицы'),
        ),
        migrations.AlterField(
            model_name='persontable',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Новый'), (1, 'Сопоставление'), (2, 'Обработано')], default=0, verbose_name='Статус'),
        ),
    ]
