# Generated by Django 4.1.6 on 2023-03-02 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_rename_filename_persontable_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='person_table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.persontable', verbose_name='Загруженная таблица'),
        ),
    ]
