# Generated by Django 4.1.6 on 2023-03-19 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_region_utc'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonStatusLV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_id', models.PositiveIntegerField(verbose_name='ID статуса')),
                ('name', models.CharField(max_length=100, verbose_name='Название статуса')),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Мужской'), ('F', 'Женский')], max_length=1, verbose_name='Пол'),
        ),
        migrations.AddField(
            model_name='person',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.personstatuslv', verbose_name='Статус'),
        ),
    ]
