# Generated by Django 4.1.6 on 2023-03-19 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_personstatuslv_person_gender_person_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personusage',
            name='date_of_use',
            field=models.DateTimeField(verbose_name='Дата использования'),
        ),
    ]
