# Generated by Django 4.1.6 on 2023-04-04 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_alter_person_gender_alter_person_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='person_usage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_person', to='core.personusage'),
        ),
    ]
