# Generated by Django 4.1.6 on 2023-04-07 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_persontable_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='product_info',
            field=models.CharField(blank=True, max_length=255, verbose_name='Информация о товаре'),
        ),
        migrations.AddField(
            model_name='person',
            name='random_number',
            field=models.BigIntegerField(default=49356471223, verbose_name='Случайное число'),
        ),
    ]
