# Generated by Django 4.1.6 on 2023-04-07 12:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_person_product_info_person_random_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='random_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Случайный UUID'),
        ),
        migrations.AlterField(
            model_name='person',
            name='random_number',
            field=models.BigIntegerField(editable=False, null=True, verbose_name='Случайное число'),
        ),
    ]
