# Generated by Django 4.1.6 on 2023-04-07 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_person_random_uuid_alter_person_random_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='random_number',
        ),
    ]
